language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script:
  - flake8 .
  - pytest --cov=. --cov-branch tests/func_tests.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
