language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script:
  - flake8 .
  - pytest --cov=main --cov-branch test_code.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
